export const SET_LOGGED_IN_USER: string = 'SET_LOGGED_IN_USER';
export const SET_PROFESSIONAL_APPLICATION: string = 'SET_PROFESSIONAL_APPLICATION';
export const SET_JNR_SNR_APPLICATION: string = 'SET_JNR_SNR_APPLICATION';
export const SET_HOD_DETAILS: string = 'SET_HOD_DETAILS';